TOP_DIR = ../..
include $(TOP_DIR)/Makefile.rules

PACKAGES = equeue,unix,equeue-ssl
OCAMLC_OPTIONS = -I ../rpc
OCAMLOPT_OPTIONS = -I ../rpc

OBJ = rpc_ssl.cmo

XOBJ = $(OBJ:.cmo=.cmx)

#COBJ = rpclocal.o

all: rpc_ssl.cma

opt: rpc_ssl.cmxa

rpc_ssl.cma: $(OBJ)
	$(OCAMLC) -o rpc_ssl.cma -a $(OBJ)

rpc_ssl.cmxa: $(XOBJ)
	$(OCAMLOPT) -o rpc_ssl.cmxa -a $(XOBJ)

include depend
