TOP_DIR=../..

PKGNAME  = rpc-ssl
ARCHIVE  = rpc_ssl
OBJECTS  = rpc_ssl.cmo
DOBJECTS = rpc_ssl.mli

INCLUDES += -I ../rpc -I ../equeue -I ../equeue-ssl

include $(TOP_DIR)/Makefile.rules

include depend
