#! /bin/sh

# Run the automated tests in this directory.
#
# Modes:
# ./test_suite clean
#   --> clean all tests
# ./test_suite make
#   --> re-make all tests (implies prior "clean")
# ./test_suite run
#   --> run the tests
# ./test_suite run_ssl
#   --> run the tests for SSL

# Debug Http_client:
#   NETLOGGED_CLIENT="Http_client Uq_engines" \
#   BENCH_ARGS=timeout-error \
#   ./test_suite -d netclient/http_bench run


top="$(dirname $PWD)"

OCAMLPATH="$top/src"
OCAMLFIND_IGNORE_DUPS_IN="$top/src"
CAML_LD_LIBRARY_PATH="$top/src/equeue-ssl:$top/src/equeue-tcl:$top/src/netstring:$top/src/netsys:$top/src/rpc-auth-local"
PATH="$top/src/rpc-generator:$PATH"

export OCAMLPATH OCAMLFIND_IGNORE_DUPS_IN CAML_LD_LIBRARY_PATH PATH

set -e 

dirs="netclient/hhamsters \
      netclient/http_bench \
      netplex/bench \
      netplex/mutex \
      netstring/bench \
      nethttpd/bench \
      netshm/bench \
      rpc/basic \
      rpc/bench \
      shell"

dirs_ssl="netclient/http_bench"


clean() {
    echo "****************************************"
    echo "Cleaning"
    echo "****************************************"
    for d in $dirs; do
	echo "----------------------------------------"
	echo ">>> Directory $d"
	echo "----------------------------------------"
	( cd $d && make clean ) || exit
    done
}


build() {
    echo "****************************************"
    echo "Building"
    echo "****************************************"
    for d in $dirs; do
	echo "----------------------------------------"
	echo ">>> Directory $d"
	echo "----------------------------------------"
	( cd $d && make build ) || exit
    done
}


run() {
    echo "****************************************"
    echo "Testing"
    echo "****************************************"
    for d in $dirs; do
	echo "----------------------------------------"
	echo ">>> Directory $d"
	echo "----------------------------------------"
	unset SSL
	( cd $d && make test ) || exit
    done
}

run_ssl() {
    echo "****************************************"
    echo "Testing (w/ SSL)"
    echo "****************************************"
    for d in $dirs_ssl; do
	echo "----------------------------------------"
	echo ">>> Directory $d"
	echo "----------------------------------------"
	( cd $d && SSL=1 make test ) || exit
    done
}


if [ $# -eq 0 ]; then
    echo "usage: ./test_suite [ -d <subdir> ] ( clean | make | run )"
    exit 0
fi

while [ $# -gt 0 ]; do
    case "$1" in
	clean)
	    shift; clean ;;
	make)
	    shift; clean && build ;;
	run)
	    shift; run ;;
	run_ssl)
	    shift; run_ssl ;;
	-d)
	    dirs="$2"
	    shift 2 ;;
	*)
	    echo "Illegal mode: $1" >&2;
	    exit 2 ;;
    esac
done

