OBJECTS  = netstring_pcre.cmo netstring_str.cmo netbuffer.cmo \
	   netaux.cmo netchannels.cmo netdate.cmo \
	   netdb.cmo netmappings.cmo netconversion.cmo netulex.cmo \
           netencoding.cmo netstream.cmo \
	   mimestring.cmo \
           nethtml_scanner.cmo nethtml.cmo \
	   neturl.cmo \
	   netaddress.cmo \
	   netmime.cmo netsendmail.cmo nethttp.cmo \

COBJECTS = netaccel_c.o

PKGNAME  = netstring

ISO_MAPPINGS   = mappings/iso*.unimap
JP_MAPPINGS    = mappings/jis*.*map
OTHER_MAPPINGS = mappings/cp*.unimap \
                 mappings/adobe*.unimap \
                 mappings/koi*.unimap \
                 mappings/mac*.unimap \
                 mappings/windows*.unimap

PMAP = netmappings_iso.pmap netmappings_other.pmap netmappings_jp.pmap

# netconversion.cmx: Allow cross-library inlining for this module

INSTALL_EXTRA = netstring_mt.cmo      netstring_mt.cmx      netstring_mt.o     \
	        netmappings_iso.cmo   netmappings_iso.cmx   netmappings_iso.o  \
	        netmappings_jp.cmo   netmappings_jp.cmx   netmappings_jp.o  \
	        netmappings_other.cmo netmappings_other.cmx netmappings_other.o\
		netmappings_min.cmo  netmappings_min.cmx netmappings_min.o \
		netconversion.cmx \
		netstring_top.cmo \
		netdb-packlist \
		dllnetaccel_c.* netaccel_link.cmo

DOBJECTS = netconversion.mli netchannels.mli netstream.mli mimestring.mli \
	netmime.mli netsendmail.mli neturl.mli netaddress.mli netbuffer.mli \
	netdate.mli netencoding.mli netulex.mli netaccel.mli \
	netaccel_link.mli nethtml.mli netstring_str.mli netstring_pcre.mli \
	netstring_mt.mli \
	netmappings.mli netaux.mli nethttp.mli

PP_OPTIONS = -package camlp4 -syntax camlp4o

INSTOTHER = install-netdb
UNINSTOTHER = uninstall-netdb

ALL_EXTRA = netstring_mt.cmo
OPT_EXTRA = netstring_mt.cmx

netdb.ml: netdb.mlp netdb.cmi
	sed -e 's|@NET_DB_DIR@|$(NET_DB_DIR)|' netdb.mlp >netdb.ml

netdb_done: tools_done $(PMAP)
	mkdir -p netdb
	cd netdb && \
		../tools/unimap_to_ocaml/unimap_to_ocaml -netdb ../*.pmap
	touch netdb_done

netmappings_iso.pmap: tools_done
	test ! -d mappings || tools/unimap_to_ocaml/unimap_to_ocaml \
		-o netmappings_iso.pmap -pmap $(ISO_MAPPINGS)

netmappings_iso.ml: netmappings_iso.pmap netdb.cmi
	tools/unimap_to_ocaml/unimap_to_ocaml \
		-o netmappings_iso.ml netmappings_iso.pmap

netmappings_jp.pmap: tools_done
	test ! -d mappings || tools/unimap_to_ocaml/unimap_to_ocaml \
		-o netmappings_jp.pmap -pmap $(JP_MAPPINGS)

#	test ! -f mappings/Unihan.txt.bz2 || \
#	   bzip2 -c -d mappings/Unihan.txt.bz2 | \
# 	   tools/unimap_to_ocaml/unihan_extract \
#	       -o netmappings_jp.pmap -jis0208 -jis0212

netmappings_jp.ml: netmappings_jp.pmap netdb.cmi
	tools/unimap_to_ocaml/unimap_to_ocaml \
		-o netmappings_jp.ml netmappings_jp.pmap

netmappings_other.pmap: tools_done
	test ! -d mappings || tools/unimap_to_ocaml/unimap_to_ocaml \
		-o netmappings_other.pmap -pmap $(OTHER_MAPPINGS)

netmappings_other.ml: netmappings_other.pmap netdb.cmi
	tools/unimap_to_ocaml/unimap_to_ocaml \
		-o netmappings_other.ml netmappings_other.pmap

netdb-packlist: netdb_done
	test -d netdb
	(cd netdb && ls *.netdb) | \
	{ while read f; do echo "$(NET_DB_DIR)/$$f"; done; } >netdb-packlist

.PHONY: install-netdb
install-netdb:
	mkdir -p $(NET_DB_DIR)
	cp netdb/*.netdb $(NET_DB_DIR)
	@echo "Installed .netdb files into $(NET_DB_DIR)"

.PHONY: uninstall-netdb
uninstall-netdb:
	if [ "$(INSTMETHOD)" = "findlib" ]; then                              \
		if packlist=`ocamlfind query $(PKGNAME)`/netdb-packlist; then \
		    if [ -f "$$packlist" ]; then                              \
			files=`cat $$packlist` &&                             \
			rm -f $$files;                                        \
			echo "Removed .netdb files";                          \
		    fi;                                                       \
		fi;                                                           \
	fi

tools_done:
	$(MAKE) -C tools
	touch tools_done

netdate.ml: netdate.mlp
	$(CAMLP4) pa_o.cmo pa_op.cmo pr_o.cmo -impl $< > $@

include $(TOP_DIR)/Makefile.rules

CLEAN_LIST += tools_done netdb_done netdb-packlist netdb.ml netdate.ml \
	 	$(PMAP:.pmap=.ml)

clean::
	test ! -d mappings || rm -f $(PMAP)
	cd tools && $(MAKE) clean

distclean::
	cd tools && $(MAKE) distclean
