(************************************************************
 * WARNING!
 *
 * This file is generated by ocamlrpcgen from the source file
 * finder_service.x
 *
 ************************************************************)
module Finder = struct
  module V1 = struct
    open Finder_service_aux
    let _program = program_Finder'V1
    
    let bind
      ?program_number
      ?version_number
      ~proc_ping
      ~proc_find
      srv
      =
        Rpc_server.bind
            ?program_number ?version_number _program 
            [
              (Rpc_server.Sync { Rpc_server.sync_name = "ping";
                                 Rpc_server.sync_proc = (fun x -> _of_Finder'V1'ping'res (proc_ping (_to_Finder'V1'ping'arg x)))});
              (Rpc_server.Sync { Rpc_server.sync_name = "find";
                                 Rpc_server.sync_proc = (fun x -> _of_Finder'V1'find'res (proc_find (_to_Finder'V1'find'arg x)))});
            ]
            srv
    
    let bind_async
      ?program_number
      ?version_number
      ~proc_ping
      ~proc_find
      srv
      =
        Rpc_server.bind
            ?program_number ?version_number _program 
            [
              (Rpc_server.Async { Rpc_server.async_name = "ping";
                                  Rpc_server.async_invoke = (fun s x -> proc_ping s (_to_Finder'V1'ping'arg x) (fun y -> Rpc_server.reply s (_of_Finder'V1'ping'res y)))});
              (Rpc_server.Async { Rpc_server.async_name = "find";
                                  Rpc_server.async_invoke = (fun s x -> proc_find s (_to_Finder'V1'find'arg x) (fun y -> Rpc_server.reply s (_of_Finder'V1'find'res y)))});
            ]
            srv
    
    end
  
end

