TOP_DIR = ../..
include $(TOP_DIR)/Makefile.rules

PACKAGES = unix ssl

OBJ = ssl_exts.cmo uq_ssl.cmo
XOBJ = $(OBJ:.cmo=.cmx)
COBJ = ssl_exts_stubs.o

OCAMLC_OPTIONS = -I ../equeue
OCAMLOPT_OPTIONS = -I ../equeue

all: equeue_ssl.cma

opt: equeue_ssl.cmxa

equeue_ssl.cma: $(OBJ) $(COBJ)
	$(OCAMLMKLIB) -o equeue_ssl $(OBJ) $(COBJ)

equeue_ssl.cmxa: $(XOBJ) $(COBJ)
	$(OCAMLMKLIB) -o equeue_ssl $(XOBJ) $(COBJ)

include depend
