#! /bin/sh

set -e

sed -e 's:\$PWD:'"$PWD:g" proto.conf > proto.conf.1

# Start the test server:
./protoserver -conf proto.conf.1 -pid $PWD/proto.pid

# Stop the test server when this script exits:
trap "kill -15 $(cat proto.pid)" EXIT

# Start the test client:
./protoclient "$@"

sleep 1

