TOP_DIR=../..

PKGNAME  = netmulticore
OBJECTS  = netmcore.cmo netmcore_camlbox.cmo
DOBJECTS = netmcore.mli netmcore_camlbox.mli

INCLUDES += $(INC_EQUEUE) $(INC_RPC) $(INC_NETSTRING) $(INC_NETSYS) \
            $(INC_NETPLEX) $(INC_NETCAMLBOX)

include $(TOP_DIR)/Makefile.rules

include depend
