TOP_DIR=../..

PRE = 1
PKGNAME = equeue-gtk2
GENERATE = META

include ./Makefile.gtk

PP_OPTIONS = -syntax camlp4o -package camlp4.macro $(GTK_DEFINES)

include $(TOP_DIR)/Makefile.rules

CLEAN_LIST += uq_gtk.ml uq_gtk.mli Makefile
