TOP_DIR=../..

PKGNAME  = rpc-auth-local
ARCHIVE  = rpc_auth_local
OBJECTS  = rpc_auth_local.cmo
COBJECTS = rpclocal.o
OCAMLDOC = 

INCLUDES += -I ../rpc

include $(TOP_DIR)/Makefile.rules

include depend
