TOP_DIR=../..

PKGNAME  = rpc-auth-local
OBJECTS  = rpc_auth_local.cmo
COBJECTS = rpclocal.o
DOBJECTS = rpc_auth_local.mli
ARCHIVE = rpc_auth_local

INCLUDES += $(INC_RPC)

include $(TOP_DIR)/Makefile.rules

include depend
