TOP_DIR=../..

PKGNAME  = shell
OBJECTS  = shell_sys.cmo shell.cmo shell_uq.cmo 
DOBJECTS = shell_sys.mli shell.mli shell_uq.mli \
	   shell_intro.txt

INCLUDES += $(INC_EQUEUE) $(INC_NETSYS)

include $(TOP_DIR)/Makefile.rules

include depend
