TOP_DIR=../..

PKGNAME  = netplex
OBJECTS  = netplex_mp.cmo
DOBJECTS = netplex_types.mli netplex_mp.mli

INCLUDES += -I ../equeue -I ../rpc -I ../shell
# Note: Instead of shell use unix-exts

include $(TOP_DIR)/Makefile.rules

include depend
