TOP_DIR = ../..
include $(TOP_DIR)/Makefile.rules

PACKAGES = unix

OBJ = rtypes.cmo syntax.cmo options.cmo parser.cmo lexer.cmo rename.cmo \
      generate.cmo main.cmo

XOBJ = $(OBJ:.cmo=.cmx)

all: ocamlrpcgen

ocamlrpcgen: $(OBJ)
	$(OCAMLC) -custom -o ocamlrpcgen $(OBJ) -linkpkg

include depend

